# $Id: Makefile.win,v 1.3 2007/12/23 16:46:17 mascarenhas Exp $

LUA_DIR= c:\lua5.1\lua
BIN_DIR= c:\lua5.1\bin

all:

install:
	IF NOT EXIST "$(LUA_DIR)\orbit" mkdir "$(LUA_DIR)\orbit"
	copy src\orbit.lua "$(LUA_DIR)"
	copy src\model.lua "$(LUA_DIR)\orbit"
	IF NOT EXIST "$(BIN_DIR)" mkdir "$(BIN_DIR)"
	copy src\orbit "$(BIN_DIR)"

install-rocks: install
	xcopy /E samples "$(PREFIX)\"
	xcopy /E doc "$(PREFIX)\"
	xcopy /E test "$(PREFIX)\"

clean:
